src/Entity/Recette.php
<?php

namespace App\Entity;

use App\Repository\RecetteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\HttpFoundation\File\File;


/**
 * @ORM\Entity(repositoryClass=RecetteRepository::class)
 *  @Vich\Uploadable
 */

class Recette
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbr_pers;

    /**
     * @ORM\Column(type="integer")
     */
    private $tps_total;

    /**
     * @ORM\Column(type="integer")
     */
    private $tps_cuisson;

    /**
     * @ORM\Column(type="integer")
     */
    private $tps_prepare;

    /**
     * @ORM\Column(type="text")
     */
    private $preparation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $category;


    /**
     * @ORM\OneToMany(targetEntity=Ingredient::class, mappedBy="recette", orphanRemoval=true, cascade={"persist"})
     */
    private $ingredients;

    /**
     * @ORM\OneToMany(targetEntity=Ustensile::class, mappedBy="recette", orphanRemoval=true, cascade={"persist"})
     */
    private $ustensiles;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="recettes")
     */
    private $user;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255)
     */
    private $fileName;

     /**
      * @var File|null
      * @Vich\UploadableField(mapping="recette_image", fileNameProperty="fileName")
      */
    private $imageFile;

    public function __construct()
    {
        $this->ingredients = new ArrayCollection();
        $this->ustensiles = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNbrPers(): ?int
    {
        return $this->nbr_pers;
    }

    public function setNbrPers(int $nbr_pers): self
    {
        $this->nbr_pers = $nbr_pers;

        return $this;
    }

    public function getTpsTotal(): ?int
    {
        return $this->tps_total;
    }

    public function setTpsTotal(int $tps_total): self
    {
        $this->tps_total = $tps_total;

        return $this;
    }

    public function getTpsCuisson(): ?int
    {
        return $this->tps_cuisson;
    }

    public function setTpsCuisson(int $tps_cuisson): self
    {
        $this->tps_cuisson = $tps_cuisson;

        return $this;
    }

    public function getTpsPrepare(): ?int
    {
        return $this->tps_prepare;
    }

    public function setTpsPrepare(int $tps_prepare): self
    {
        $this->tps_prepare = $tps_prepare;

        return $this;
    }

  
    public function getPreparation(): ?string
    {
        return $this->preparation;
    }

    public function setPreparation(string $preparation): self
    {
        $this->preparation = $preparation;

        return $this;
    }

    /**
     * @return Collection|Ingredient[]
     */
    public function getIngredients(): Collection
    {
        return $this->ingredients;
    }

    public function addIngredient(Ingredient $ingredient): self
    {
        if (!$this->ingredients->contains($ingredient)) {
            $this->ingredients[] = $ingredient;
            $ingredient->setRecette($this);
        }

        return $this;
    }

    public function removeIngredient(Ingredient $ingredient): self
    {
        if ($this->ingredients->removeElement($ingredient)) {
            // set the owning side to null (unless already changed)
            if ($ingredient->getRecette() === $this) {
                $ingredient->setRecette(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Ustensile[]
     */
    public function getUstensiles(): Collection
    {
        return $this->ustensiles;
    }

    public function addUstensile(Ustensile $ustensile): self
    {
        if (!$this->ustensiles->contains($ustensile)) {
            $this->ustensiles[] = $ustensile;
            $ustensile->setRecette($this);
        }

        return $this;
    }

    public function removeUstensile(Ustensile $ustensile): self
    {
        if ($this->ustensiles->removeElement($ustensile)) {
            // set the owning side to null (unless already changed)
            if ($ustensile->getRecette() === $this) {
                $ustensile->setRecette(null);
            }
        }

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * Get the value of fileName
     *
     * @return  string|null
     */ 
    public function getFileName()
    {
        return $this->fileName;
    }

    /**
     * Set the value of fileName
     *
     * @param  string|null  $fileName
     *
     * @return  self
     */ 
    public function setFileName($fileName)
    {
        $this->fileName = $fileName;

        return $this;
    }
    

    /**
     * Get the value of category
     */ 
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set the value of category
     *
     * @return  self
     */ 
    public function setCategory($category)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get the value of imageFile
     *
     * @return  File|null
     */ 
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * Set the value of imageFile
     *
     * @param  File|null  $imageFile
     *
     * @return  self
     */ 
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;

        return $this;
    }
}

src/Controller/RecetteController.php
<?php

namespace App\Controller;

use App\Entity\Recette;
use App\Repository\RecetteRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RecetteController extends AbstractController
{
    /**
     * @Route("/recette", name="recette")
     */
    public function index(RecetteRepository $recetteRepository): Response
    {
        
        $resultat=$recetteRepository->findBy([], ['id'=> 'DESC'],6,0 );
        
        $resultats=$recetteRepository->findBy([], ['tps_total'=> 'ASC'],5,0 );      

        return $this->render('recette/recette.html.twig', [
            'recettes'=> $resultat,
            'results'=> $resultats, 
    
        ]);
    }

    /**
     * @Route("/recette_list", name="recette_list")
     */

    public function recetteList(RecetteRepository $recetteRepository): Response
    {       
        return $this->render('recette/recette_list.html.twig', [
            'recette_list' => $recetteRepository->findAll(),
            
        ]);

    }

      /**
     * @Route("/recette_cat/{id}", name="recette_cat",  methods={"GET","HEAD"})
     * 
     */

    public function recetteCat(int $id, RecetteRepository $recetteRepository): Response
    { 
    
    
        // return $this->render('recette/recette_cat.html.twig',[
        //  'cat_recette' => $recetteRepository->findBy([], ['category'=> $id]),
           
        //  ]);

    }

    /**
     * @Route("/recette/{id<\d+>}", name="recette_page")
     * Le FrameworkExtraBundle a installée le ParamConverter qui permet de convertir des paramètres de route en autre chose 
     * Il est capable de convertir des paramètres en entités sans aucune configuration supplémentaire
     */


    public function recettePage(Recette $recette): Response
    {
        return $this->render('recette/recette_page.html.twig', [
            'recette' => $recette
        ]);
    }


}

templates/recette/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello RecetteController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/Pham/Desktop/GIT PROJET/pamekitchen-sf4/src/Controller/RecetteController.php'|file_link(0) }}">src/Controller/RecetteController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/Pham/Desktop/GIT PROJET/pamekitchen-sf4/templates/recette/index.html.twig'|file_link(0) }}">templates/recette/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/recette/recette.html.twig
{% extends "_template.html.twig" %}

{% block content %}

    <section id = "listRecettes" class= "dimension"> 

        <h2>Les dernières recettes irrésistibles </h2>
        
            <div class= "container"> 

                <div class = "row">  
                 {% for recette in recettes %}
           
                    <div class = "col-6">  

                        <div class="recette_img">
                    
                            <a href="{{path ('recette_page', {id: recette.id})}}">
                                <img src="{{asset ('images/recettes/' ~ recette.fileName)}}" alt="image" style="width:100%;">
                            </a>
                            <div class= "titre_recette">
                                <a href="{{path ('recette_page', {id: recette.id})}}">{{recette.name}}</a>
                            </div>
                        
                        </div>
                    </div>
                 {% endfor %}
                </div>
            </div>
       
        <hr class="separated">
        
        <div class="top_recette">
            <h2>Les recettes les plus faciles</h2>
             <div class="titleRecettes">

                {% for r in results %}

                    <p><a href="{{path ('recette_page', {id: r.id} )}}">{{r.name}}</a><p>

                {% endfor %}

            </div>
                      
        <div>
    </section>

{% endblock %}

templates/recette/recette_cat.html.twig
{% extends "_template.html.twig" %}

{% block content %}

        
    {% endfor %}
{% endblock %}

templates/recette/recette_list.html.twig
{% extends "_template.html.twig" %}

{% block content %}

    <div class="dimension">

        <h2> Nombre de recettes: {{ recette_list|length }}</h2>
      
        <div class="container">

         <div class="row align-items-start">      
                <div class="col-8"> 
                 {% for r in recette_list %}           
                    <article class="media">
                       
                        <div class="media-body">
                            <figure class="figure">
                               <img src="{{asset ('images/recettes/' ~ r.fileName)}}" alt="Image" style="width: 300px; heigth: 300px">
                            </figure>
                        </div>
                        <div class="media-body">
                                <p>
                                    <a href="{{ path ('recette_page', {id: r.id})}}" class="has-text-primary">
                                        <strong>{{r.name}}</strong>
                                    </a> <br>
                                    {# On affiche uniquement les 50 premiers caractères de la description #}
                                  
                                </p>

                                <p>  <b> Description: </b> {{ r.description|slice(0, 50) }}</p>

                                <b>Ingrédients : </b> 

                                {% for ingredient in r.ingredients %}                                        
                                    <span> {{ ingredient.quantite}} {{ingredient.nom }}, </span>
                                {% endfor %}

                                <p> <b>Temps total </b>
                                <i class="far fa-clock">:</i>                       
                                 {{r.tpsTotal}} min </p>
                         
                        </div>

                    </article>

                     {% endfor %}
                   
                </div>
                
             </div>
        
        </div>
    </div>
{% endblock %}

templates/recette/recette_page.html.twig
{% extends "_template.html.twig" %}

{% block content %}
    <div class="dimension">
     
        <h2>{{ recette.name }}</h2>
                 
        <div class="media-body">
                <figure class="figure">
                     <img src="{{asset ('images/recettes/' ~ recette.fileName)}}" alt="{{recette.name}}" class="card-img-top">
                </figure>
        </div>

        <div class="media-body">
            <p>{{ recette.description }}</p>

            <p>Recette pour {{ recette.nbrPers }} personnes</p> 

            <b> Ingrédients: </b>
            {% for ingredient in recette.ingredients %}
                <span> {{ ingredient.quantite }} {{ ingredient.nom }}, </span>
            {% endfor %} 
            <br>

            <b> Ustensiles: </b>
            {% for ustensile in recette.ustensiles %}
                <span>  {{ ustensile.nom }}, </span>
            {% endfor %}

            <p> <b>Temps total </b>
                <i class="far fa-clock">:</i>                       
                    {{recette.tpsTotal}} min                    
            </p>

             <p> <b>Temps de préparation </b>
                <i class="far fa-clock">:</i>                       
                    {{recette.tpsPrepare}} min                    
            </p>

             <p> <b>Temps de cuisson </b>
                <i class="far fa-clock">:</i>                       
                    {{recette.tpsCuisson}} min                    
            </p>
            <p> <b>Les étapes à préparer: </b> {{ recette.preparation }}</p>
        </div>
    
   </div>
     
{% endblock %}

 